### ISSUE TITLE
SSH connection

### ISSUE THREAD

**Issue by Rayn93** [OXID-eSales/docker-eshop-sdk#25]
Hi

Thanks for nice docker setup for Oxid.
Is it possible to connect with container via SSH? I will create a module for Oxid and SSH connection will be very helpful for my developer environment.

**Comment by Sieg** [comment]
Hey @Rayn93, could you tell more about your question? Why do you need ssh connection? By using the `make php` or the full variant `docker compose exec php bash` you will be in container, is that what you need? :)

**Comment by Sieg** [comment]
Closing it for now, please reopen if you still have the issue and we can do something about it.
