### ISSUE TITLE
Docker with PHP 7.1 pulls the wrong composer version

### ISSUE THREAD

**Issue by oxidMichaelWalter** [OXID-eSales/docker-eshop-sdk#27]
When using the PHP 7.1 Docker container, it always pulls the latest version of composer:
https://github.com/OXID-eSales/docker/blob/dddf4c4516171480c7ab055a2336c39319aa615e/php/Dockerfile#L49

That's a problem, because composer 2.3 will be installed, but they dropped the support for PHP 7.1.
We would need composer 2.2 to actually work with this container.

**Comment by joernott** [comment]
@oxidMichaelWalter, I fixed that in our master branch by pinning the version to 2.2. 
However, looking at the automated builds (https://github.com/OXID-eSales/docker/actions/runs/9709085731), we dropped automatic building and pushing images to docker hub for 7.0 to 7.3 about a year ago.

So, if you rely on those pre-built images, we need to re-add build actions for those older versions, too

**Comment by joernott** [comment]
I have added a build script that can be triggered manually. Sadly, I could not get it to work for 7.0/7.2 and 7.3 but miraculously, 7.1 worked fine. So we now have a new PHP 7.1 image: https://hub.docker.com/layers/oxidesales/oxideshop-docker-php/7.1/images/sha256-867bf1c8c4a0bffef9247de98bc14ca7bb82ba1c583d3f555443937962788bc5?context=explore

**Comment by Sieg** [comment]
@oxidMichaelWalter please report if there will be problems with those other versions and you guys will need those older images, so Jorn then will invest Time into those, but if its good enough for now, then all fine.
